GitHub actions
webdjoe/pyvesync pull request #186
Opened 2023-05-09 02:52 UTC by sdrapha

I'm not sure if you are interested on github actions, but I did it anyway.
I know there are currently azure-pipelines already there. But the github version of workflows integrates so well both on web interface, app, notifications, etc. so I'm just putting it out there.

It's possible to improve it a bit, breaking out flake8, mypy and pylint in different threads, but for now, just converting the existing azure pipeline structure works well.

2023-05-09 03:05 UTC, sdrapha commented
Note that, when I created this PR, all github actions run prrety fast and were completely done ( including an extra one python 3.11 ), and the azure ones hadn't even started yet at that moment. 
Seems there is a performance difference.
Not that the extra 40 secs of waiting on the azure ones would hurt anybody though.

2025-01-25 00:02 UTC, cdnninja requested changes

2025-01-25 00:02 UTC, cdnninja commented on .github/workflows/tests.yml
> +          - '3.8'
3.8 fail so should be removed since I think this needs 3.9

2025-01-25 00:03 UTC, cdnninja commented
Outside of tests I am a big fan of pre-commit instead of github actions for linting.   It auto corrects items it can in the PRs plus consumes the precommit files that VS code uses so just enforces those same items. https://[pre-commit.ci](https://pre-commit.ci/)/

2025-10-11 20:31 UTC, cdnninja commented
I think github actions are now used, I suspect this can be closed?

2026-02-10 00:51 UTC, sdrapha commented
No longer needed

2026-02-10 00:51 UTC, closed without merging